export const ASSET_TYPES = [
  { code: 'HW', label: 'Hardware' },
  { code: 'MP', label: 'Mobile/Portable' },
  { code: 'NI', label: 'Network/Infra' },
  { code: 'SD', label: 'Server/Data Center' },
  { code: 'SS', label: 'Software/Subscriptions' },
  { code: 'PA', label: 'Peripherals & Accessories' },
  { code: 'IT', label: 'IoT' },
];

export const ASSET_CATEGORIES = {
  'HW': [
    { code: 'LTP', label: 'Laptop' },
    { code: 'CPU', label: 'PC / CPU' },
    { code: 'AIO', label: 'All In One' },
    { code: 'KSK', label: 'Kiosk' },
  ],
  'MP': [
    { code: 'TAB', label: 'Table' },
    { code: 'SMA', label: 'Smartphone' },
    { code: 'MBP', label: 'Mobile Barcode Phone' },
    { code: 'HHS', label: 'Handheld Scanner' },
    { code: 'GPS', label: 'GPS Unit' },
  ],
  'NI': [
    { code: 'RTR', label: 'Router' },
    { code: 'SWI', label: 'Switch' },
    { code: 'FIR', label: 'Firewall' },
    { code: 'ACC', label: 'Access Point' },
    { code: 'PPL', label: 'Patch Panel' },
    { code: 'RAC', label: 'Rack' },
    { code: 'UPS', label: 'UPS' },
    { code: 'PDU', label: 'PDU' },
  ],
  'SD': [
    { code: 'PHS', label: 'Physical Server' },
    { code: 'CLS', label: 'Cloud Server' },
    { code: 'NAS', label: 'SAN/NAS' },
  ],
  'SS': [
    { code: 'IHS', label: 'In House' },
    { code: 'OPL', label: 'On-premise license (perpetual, subscription)' },
    { code: 'SAS', label: 'Software as A Service' },
    { code: 'IAS', label: 'Infrastructure as A Service' },
    { code: 'PAS', label: 'Platform as A Service' },
    { code: 'VMI', label: 'Virtual Machine Image' },
    { code: 'CDK', label: 'Container-Docker / Kubernetes' },
    { code: 'API', label: 'API Key' },
  ],
  'PA': [
    { code: 'MON', label: 'Monitor' },
    { code: 'KEY', label: 'Keyboard' },
    { code: 'MOS', label: 'Mouse' },
    { code: 'DOC', label: 'Docking Station' },
    { code: 'SCN', label: 'Scanner' },
    { code: 'PJR', label: 'Projector' },
    { code: 'PRI', label: 'Printer' },
    { code: 'HEA', label: 'Headset' },
    { code: 'SPR', label: 'Speaker (Speaker PC)' },
    { code: 'WBM', label: 'Webcam' },
    { code: 'VRH', label: 'VR Headset' },
  ],
  'IT': [
    { code: 'CTV', label: 'CCTV' },
    { code: 'FIP', label: 'Fingerprint' },
    { code: 'NFC', label: 'RFID Reader' },
    { code: 'IFP', label: 'Interactive Flat Panel' },
    { code: 'STV', label: 'Smart TV' },
    { code: 'VID', label: 'Videotron' },
  ],
};

export const ASSET_SUBCATEGORIES = {
  'CTV': [
    { code: 'NVR', label: 'NVR' },
    { code: 'DVR', label: 'DVR' },
    { code: 'IPO', label: 'CCTV IP Outdoor' },
    { code: 'IPI', label: 'CCTV IP Indoor' },
    { code: 'ANI', label: 'Analog Indoor' },
    { code: 'ANO', label: 'Analog Outdoor' },
  ],
  'CLS': [
    { code: 'ABB', label: 'Alibaba' },
    { code: 'AWS', label: 'AWS' },
    { code: 'AZR', label: 'Azure' },
    { code: 'ERA', label: 'Eranyacloud' },
    { code: 'GCP', label: 'Google Cloud' },
  ],
  'NAS': [
    { code: 'DES', label: 'Desktop' },
    { code: 'MOU', label: 'Mounting' },
    { code: 'HDD', label: 'HDD Data' },
    { code: 'HDS', label: 'HDD Surveillance' },
    { code: 'SSD', label: 'SSD' },
    { code: 'RAM', label: 'RAM' },
  ],
  'KEY': [
    { code: 'KBL', label: 'Wired' },
    { code: 'WLS', label: 'Wireless' },
  ],
  'PRI': [
    { code: 'INK', label: 'Ink' },
    { code: 'LSR', label: 'Laser' },
  ],
};

export const TABLE_COLUMNS = [
  { key: 'barcode', label: 'Barcode IT', minWidth: 'w-48', showAlways: true },
  { key: 'city_code', label: 'Kota', minWidth: 'w-20', showAlways: true },
  
  { key: 'type_code', label: 'Tipe', minWidth: 'w-20', showAlways: true },
  { key: 'category_code', label: 'Kategori', minWidth: 'w-24', showAlways: true },
  { key: 'subcategory_code', label: 'Jenis', minWidth: 'w-24', showAlways: true },

  { key: 'procurement_month', label: 'Bln', minWidth: 'w-16', showAlways: true },
  { key: 'procurement_year', label: 'Thn', minWidth: 'w-16', showAlways: true },

  { key: 'floor', label: 'Lantai', minWidth: 'w-20', showAlways: true },
  { key: 'sequence_number', label: 'No Urut', minWidth: 'w-24', showAlways: true },
  { key: 'placement', label: 'Penempatan', minWidth: 'w-32', showAlways: true },
  
  { key: 'brand', label: 'Brand', minWidth: 'w-32', showAlways: true },
  { key: 'room', label: 'Ruangan', minWidth: 'w-32', showAlways: true },
  { key: 'model_series', label: 'Tipe/Seri', minWidth: 'w-40', showAlways: true },

  { key: 'ip_address', label: 'IP Address', minWidth: 'w-36', showAlways: true },
  { key: 'mac_address', label: 'MAC Address', minWidth: 'w-36', showAlways: true },
  { key: 'serial_number', label: 'Serial Number', minWidth: 'w-40', showAlways: true },

  { key: 'status', label: 'Status', minWidth: 'w-32', showAlways: true },

  { key: 'processor', label: 'Processor', minWidth: 'w-32', showAlways: false },
  { key: 'ram', label: 'RAM', minWidth: 'w-24', showAlways: false },
  { key: 'storage', label: 'Storage', minWidth: 'w-24', showAlways: false },
  { key: 'os', label: 'OS', minWidth: 'w-24', showAlways: false },

  { key: 'connect_to', label: 'Connect To', minWidth: 'w-32', showAlways: false },
  { key: 'channel', label: 'Channel', minWidth: 'w-24', showAlways: false },

  { key: 'username', label: 'Username', minWidth: 'w-32', showAlways: false },
  { key: 'password', label: 'Password', minWidth: 'w-32', showAlways: false },
  { key: 'assigned_to', label: 'Pengguna', minWidth: 'w-32', showAlways: false },
];

export const CITIES = [
  { code: '00', label: 'Yayasan' },
  { code: '01', label: 'Jakarta' },
  { code: '02', label: 'Bandar Lampung' },
  { code: '03', label: 'Bandung' },
  { code: '04', label: 'Bogor' },
  { code: '05', label: 'Cianjur' },
  { code: '06', label: 'Cicurug' },
  { code: '07', label: 'Cimahi' },
  { code: '08', label: 'Cirebon' },
  { code: '09', label: 'Indramayu' },
  { code: '10', label: 'Jatibarang' },
  { code: '11', label: 'Metro' },
  { code: '12', label: 'Rengasdengklok' },
  { code: '13', label: 'Serang' },
  { code: '14', label: 'Sukabumi' },
  { code: '15', label: 'Tasikmalaya' },
  { code: '99', label: 'Tirtamarta' },
];

export const FLOORS = [
  'B3', 'B2', 'B1', '01', '02', '03', '04', '05', 
  '06', '07', '08', '09', '10', '11', '12', '13', '14', '15'
];

export const SCHOOL_CODE_MAPPING = {
'PENABUR Junior College Tanjung Duren': 'A08',
'PENABUR Intercultural School Secondary Tanjung Duren': 'P08',
'SDK 11 - Sunrise Garden': 'D11',
'SMAK 1 - Tanjung Duren': 'A01',
'SMAK 4 - Sunrise Garden': 'A04',
'SMPK 7 - Sunrise Garden': 'P07',
'TKK 11 - Sunrise Garden': 'K11',
'SDK 1 - Samanhudi': 'D01',
'SDK 2 - Pembangunan': 'D02',
'SDK 3 - Gunung Sahari': 'D03',
'SMAK 2 - Pintu Air': 'A02',
'SMAK 3 - Gunung Sahari': 'A03',
'SMK Farmasi BPK Penabur Jakarta': 'AMF',
'SMPK 1 - Pintu Air': 'P01',
'SMPK 2 - Pembangunan': 'P02',
'SMPK 3 - Gunung Sahari': 'P03',
'TKK 1 - Samanhudi': 'K01',
'TKK 2 - Pembangunan': 'K02',
'TKK 7 - Gunung Sahari': 'K07',
'PENABUR Intercultural School Primary Kelapa Gading': 'DKG',
'PENABUR Intercultural School Secondary Kelapa Gading': 'PKG',
'PENABUR Junior College Kelapa Gading': 'AKG',
'SDK 10 - Pantai Indah Kapuk': 'D10',
'SDK 6 - Kelapa Gading': 'D06',
'SMAK 5 - Kelapa Gading': 'A05',
'SMAK 6 - Muara Karang': 'A06',
'SMPK 4 - Kelapa Gading': 'P04',
'SMPK 6 - Muara Karang': 'P06',
'TKK 10 - Pantai Indah Kapuk': 'K10',
'TKK 6 - Kelapa Gading': 'K06',
'SDK 4 - Cipinang Indah': 'D04',
'SDK 8 - Cawang': 'D08',
'SMAK 7 - Cipinang Indah': 'A07',
'SMPK 5 - Cipinang Indah': 'P05',
'TKK 3 - Cipinang Indah': 'K03',
'TKK 5 - Taman Mini': 'K05',
'TKK 8 - Cawang': 'K08',
'SDK 9 - Setiabudi': 'D09',
'TKK 9 - Setiabudi': 'K09',
'SDK TirtaMarta - Pondok Indah': 'DPI',
'SMAK TirtaMarta - Pondok Indah': 'API',
'SMPK TirtaMarta - Pondok Indah': 'PPI',
'TKK TirtaMarta - Pondok Indah': 'KPI',
'SDK Bintaro Jaya': 'DBJ',
'SDK Gading Serpong': 'DGS',
'SDK Kota Modern': 'DKM',
'SMAK Bintaro Jaya': 'ABJ',
'SMAK Gading Serpong': 'AGS',
'SMAK Kota Tangerang': 'AKT',
'SMPK Bintaro Jaya': 'PBJ',
'SMPK Gading Serpong': 'PGS',
'SMPK Kota Modern': 'PKM',
'TKK Bintaro Jaya': 'KBJ',
'TKK Gading Serpong': 'KGS',
'TKK Kota Modern': 'KKM',
'SDK Agus Salim': 'DAS',
'SDK Harapan Indah': 'DHI',
'SDK Kota Jababeka': 'DKJ',
'SDK Summarecon Bekasi': 'DSB',
'SMAK Harapan Indah': 'AHI',
'SMAK Kota Jababeka': 'AKJ',
'SMAK Summarecon Bekasi': 'ASB',
'SMPK Harapan Indah': 'PHI',
'SMPK Kota Jababeka': 'PKJ',
'SMPK Summarecon Bekasi': 'PSB',
'TKK Agus Salim': 'KAS',
'TKK Harapan Indah': 'KHI',
'TKK Kota Jababeka': 'KKJ',
'TKK Summarecon Bekasi': 'KSB',
'SDK Kota Wisata': 'DKW',
'SMAK Kota Wisata': 'AKW',
'SMPK Kota Wisata': 'PKW',
'TKK Kota Wisata': 'KKW',
'SDK Depok': 'DDP',
'SDK TirtaMarta - Cinere': 'DCN',
'SMPK Depok': 'PDP',
'SMPK TirtaMarta - Cinere': 'PCN',
'TKK Depok': 'KDP',
'TKK TirtaMarta - Cinere': 'KCN'
};