"""Add user profile fields

Revision ID: 54a2929c79e5
Revises: bbd6aa7223e1
Create Date: 2025-11-29 00:18:56.537731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a2929c79e5'
down_revision: Union[str, Sequence[str], None] = 'bbd6aa7223e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'full_name') # Jangan lupa hapus juga saat downgrade
    # ### end Alembic commands ###