"""Add update logs table

Revision ID: bbd6aa7223e1
Revises: f1fdff577185
Create Date: 2025-11-28 22:57:10.602387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd6aa7223e1'
down_revision: Union[str, Sequence[str], None] = 'f1fdff577185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_barcode', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_logs_asset_barcode'), 'update_logs', ['asset_barcode'], unique=False)
    op.create_index(op.f('ix_update_logs_id'), 'update_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_update_logs_id'), table_name='update_logs')
    op.drop_index(op.f('ix_update_logs_asset_barcode'), table_name='update_logs')
    op.drop_table('update_logs')
    # ### end Alembic commands ###
