"""Add service history table

Revision ID: f1fdff577185
Revises: 47a9f8a296d9
Create Date: 2025-11-28 19:04:55.934168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fdff577185'
down_revision: Union[str, Sequence[str], None] = '47a9f8a296d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_no', sa.String(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=True),
    sa.Column('sn_or_barcode', sa.String(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('issue_description', sa.String(length=30), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_histories_id'), 'service_histories', ['id'], unique=False)
    op.create_index(op.f('ix_service_histories_sn_or_barcode'), 'service_histories', ['sn_or_barcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_histories_sn_or_barcode'), table_name='service_histories')
    op.drop_index(op.f('ix_service_histories_id'), table_name='service_histories')
    op.drop_table('service_histories')
    # ### end Alembic commands ###
